[package]
name = "server-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
ort = "1.15.2"
tracing-subscriber = { version = "0.3.17", features = [ "env-filter", "fmt" ] }
ndarray = "0.15.6"
csv = "1.2.2"
